/**
 * GENERATED by scripts/fetch-logos.mjs. Do not edit by hand.
 *
 * Intrinsic dimensions of the WebP files in public/logos. The component renders
 * these as the img width and height attributes so the browser reserves the
 * right box before the bytes arrive, which is what holds CLS at zero.
 *
 * The rendered height is half of what is listed here: the assets are 2x.
 */

export interface TrustLogo {
  readonly id: string;
  readonly label: string;
  readonly src: string;
  /** Intrinsic width of the 2x asset. */
  readonly width: number;
  /** Intrinsic height of the 2x asset. */
  readonly height: number;
}

export const TRUST_LOGOS: readonly TrustLogo[] = [
  { id: "amazon", label: "Amazon", src: "/logos/amazon.webp", width: 159, height: 48 },
  { id: "google", label: "Google", src: "/logos/google.webp", width: 133, height: 44 },
  { id: "microsoft", label: "Microsoft", src: "/logos/microsoft.webp", width: 192, height: 41 },
  { id: "flipkart", label: "Flipkart", src: "/logos/flipkart.webp", width: 174, height: 46 },
  { id: "atlassian", label: "Atlassian", src: "/logos/atlassian.webp", width: 243, height: 30 },
  { id: "phonepe", label: "PhonePe", src: "/logos/phonepe.webp", width: 169, height: 46 },
  { id: "deloitte", label: "Deloitte", src: "/logos/deloitte.webp", width: 192, height: 36 },
  { id: "navi", label: "Navi", src: "/logos/navi.webp", width: 161, height: 43 },
] as const;
