/**
 * GENERATED by scripts/fetch-plan-media.mjs. Do not edit by hand.
 *
 * The two plan images are emitted at two widths each and described here as a
 * ready-made srcset. Both share identical dimensions at each width, which is
 * what lets the comparison slider wipe between them without the framing
 * shifting. width and height are the LARGEST variant, used to give the box its
 * aspect ratio so nothing shifts while the image loads.
 */

export interface PlanImage {
  readonly src: string;
  readonly srcSet: string;
  readonly width: number;
  readonly height: number;
}

export const PLAN_IMAGES: Readonly<Record<"broker" | "propsoch", PlanImage>> = {
  broker: {
    src: "/plan/broker-990.webp",
    srcSet: "/plan/broker-660.webp 660w, /plan/broker-990.webp 990w",
    width: 990,
    height: 660,
  },
  propsoch: {
    src: "/plan/propsoch-990.webp",
    srcSet: "/plan/propsoch-660.webp 660w, /plan/propsoch-990.webp 990w",
    width: 990,
    height: 660,
  },
};

export const PROCESS_AVATAR = {
  src: "/plan/roshik-shenoy.webp",
  width: 96,
  height: 96,
} as const;
