// Generated by scripts/fetch-plan-media.mjs. Do not edit by hand.
export interface PlanImage {
  readonly src: string;
  readonly srcSet: string;
  readonly width: number;
  readonly height: number;
}

export const PLAN_IMAGES: Readonly<Record<"broker" | "propsoch", PlanImage>> = {
  broker: {
    src: "/plan/broker-990.webp",
    srcSet: "/plan/broker-660.webp 660w, /plan/broker-990.webp 990w",
    width: 990,
    height: 660,
  },
  propsoch: {
    src: "/plan/propsoch-990.webp",
    srcSet: "/plan/propsoch-660.webp 660w, /plan/propsoch-990.webp 990w",
    width: 990,
    height: 660,
  },
};

export const PROCESS_AVATAR = {
  src: "/plan/roshik-shenoy.webp",
  width: 96,
  height: 96,
} as const;
