/**
 * GENERATED by scripts/fetch-posters.mjs. Do not edit by hand.
 *
 * Intrinsic dimensions of the poster WebPs in public/posters. The card renders
 * these as the img width and height so the browser reserves a correctly shaped
 * box before the bytes arrive, which is what holds CLS at zero while three
 * lazy images stream in.
 */

export interface VideoPoster {
  readonly src: string;
  readonly width: number;
  readonly height: number;
}

/** Keyed by YouTube id, the same ids used by TESTIMONIALS in lib/content.ts. */
export const POSTERS: Readonly<Record<string, VideoPoster>> = {
  "OZMT9fgbH_c": { src: "/posters/OZMT9fgbH_c.webp", width: 720, height: 405 },
  "Nid3XKVEApg": { src: "/posters/Nid3XKVEApg.webp", width: 720, height: 405 },
  "XrsfHS7tCN0": { src: "/posters/XrsfHS7tCN0.webp", width: 720, height: 405 },
};
