// Generated by scripts/fetch-posters.mjs. Do not edit by hand.
export interface VideoPoster {
  readonly src: string;
  readonly width: number;
  readonly height: number;
}

export const POSTERS: Readonly<Record<string, VideoPoster>> = {
  "OZMT9fgbH_c": { src: "/posters/OZMT9fgbH_c.webp", width: 720, height: 405 },
  "Nid3XKVEApg": { src: "/posters/Nid3XKVEApg.webp", width: 720, height: 405 },
  "XrsfHS7tCN0": { src: "/posters/XrsfHS7tCN0.webp", width: 720, height: 405 },
};
