/**
 * GENERATED by scripts/fetch-media-logos.mjs. Do not edit by hand.
 *
 * Each logo carries its intrinsic size, so the row reserves its boxes before
 * any bytes arrive, and the URL of the article it refers to.
 */

export interface PressLogo {
  readonly src: string;
  readonly name: string;
  readonly href: string;
  readonly width: number;
  readonly height: number;
}

export const PRESS_LOGOS: readonly PressLogo[] = [
  {
    src: "/press/the-print.webp",
    name: "The Print",
    href: "https://theprint.in/ani-press-releases/propsoch-redefines-homebuying-in-india-with-their-buyer-centric-advisory-model/2552423/",
    width: 190,
    height: 60,
  },
  {
    src: "/press/ani.webp",
    name: "ANI",
    href: "https://www.aninews.in/news/business/propsoch-redefines-homebuying-in-india-with-their-buyer-centric-advisory-model20250318121741/",
    width: 143,
    height: 60,
  },
  {
    src: "/press/business-standard.webp",
    name: "Business Standard",
    href: "https://www.business-standard.com/content/press-releases-ani/propsoch-redefines-homebuying-in-india-with-their-buyer-centric-advisory-model-125031800520_1.html",
    width: 269,
    height: 60,
  },
  {
    src: "/press/mint.webp",
    name: "Mint",
    href: "https://www.business-standard.com/content/press-releases-ani/propsoch-redefines-homebuying-in-india-with-their-buyer-centric-advisory-model-125031800520_1.html",
    width: 123,
    height: 60,
  },
  {
    src: "/press/realty-next.webp",
    name: "Realty NXT",
    href: "https://realtynxt.com/proptech-buzz/2025-02-18/propsoch-raises-500k-to-transform-home-buying-with-data-science-unbiased-insights-realtynxt-exclusive",
    width: 107,
    height: 60,
  },
];
