import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

// Downloads the employer logos from Propsoch's CDN, converts to WebP and writes
// lib/logos.generated.ts with each file's intrinsic size.
const CDN = "https://d1zk2x7mtoyb2b.cloudfront.net/websiteAssets/logos";

const TARGET_H = 48;

const OUT_DIR = path.join(process.cwd(), "public", "logos");
const MANIFEST = path.join(process.cwd(), "lib", "logos.generated.ts");

const LOGOS = [
  { id: "amazon", label: "Amazon", file: "amazon-logo.png", scale: 1.0 },
  { id: "google", label: "Google", file: "google-logo.png", scale: 0.92 },
  { id: "microsoft", label: "Microsoft", file: "microsoft-logo.png", scale: 0.85 },
  { id: "flipkart", label: "Flipkart", file: "flipkart-logo.webp", scale: 0.95 },
  { id: "atlassian", label: "Atlassian", file: "atlassian-logo.webp", scale: 0.62 },
  { id: "phonepe", label: "PhonePe", file: "PhonePe-Logo.webp", scale: 0.95 },
  { id: "deloitte", label: "Deloitte", file: "Deloitte-Logo.png", scale: 0.74 },
  { id: "navi", label: "Navi", file: "navi-logo.png", scale: 0.9 },
];

async function whiteToAlpha(input) {
  const { data, info } = await sharp(input)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const out = Buffer.alloc(data.length);
  for (let i = 0; i < data.length; i += 4) {
    const r = data[i];
    const g = data[i + 1];
    const b = data[i + 2];
    const a = 255 - Math.min(r, g, b);

    if (a === 0) {
      out[i] = out[i + 1] = out[i + 2] = out[i + 3] = 0;
      continue;
    }

    const white = 255 - a;
    out[i] = Math.max(0, Math.min(255, Math.round(((r - white) * 255) / a)));
    out[i + 1] = Math.max(0, Math.min(255, Math.round(((g - white) * 255) / a)));
    out[i + 2] = Math.max(0, Math.min(255, Math.round(((b - white) * 255) / a)));
    out[i + 3] = a;
  }

  return sharp(out, {
    raw: { width: info.width, height: info.height, channels: 4 },
  })
    .png()
    .toBuffer();
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const results = [];
  let totalBytes = 0;

  for (const logo of LOGOS) {
    const url = `${CDN}/${logo.file}`;
    const res = await fetch(url, { headers: { "user-agent": "Mozilla/5.0" } });
    if (!res.ok) throw new Error(`${logo.id}: HTTP ${res.status} for ${url}`);
    let buf = Buffer.from(await res.arrayBuffer());

    const meta = await sharp(buf).metadata();
    const hadAlpha = Boolean(meta.hasAlpha);
    if (!hadAlpha) buf = await whiteToAlpha(buf);

    const trimmed = await sharp(buf).trim({ threshold: 10 }).toBuffer();

    const height = Math.round(TARGET_H * logo.scale);
    const out = await sharp(trimmed)
      .resize({ height, fit: "inside", withoutEnlargement: false, kernel: "lanczos3" })
      .webp({ quality: 90, alphaQuality: 100, effort: 6 })
      .toBuffer({ resolveWithObject: true });

    const outPath = path.join(OUT_DIR, `${logo.id}.webp`);
    await writeFile(outPath, out.data);
    totalBytes += out.data.length;

    results.push({
      id: logo.id,
      label: logo.label,
      width: out.info.width,
      height: out.info.height,
      bytes: out.data.length,
      hadAlpha,
      source: meta.width + "x" + meta.height + " " + meta.format,
    });

    console.log(
      `  ${logo.id.padEnd(10)} ${String(meta.width + "x" + meta.height).padEnd(11)} -> ` +
        `${String(out.info.width + "x" + out.info.height).padEnd(9)} ` +
        `${String(out.data.length).padStart(5)}B` +
        (hadAlpha ? "" : "  (white keyed to alpha)")
    );
  }

  const ts = `// Generated by scripts/fetch-logos.mjs. Do not edit by hand.

export interface TrustLogo {
  readonly id: string;
  readonly label: string;
  readonly src: string;
  /** Intrinsic width of the 2x asset. */
  readonly width: number;
  /** Intrinsic height of the 2x asset. */
  readonly height: number;
}

export const TRUST_LOGOS: readonly TrustLogo[] = [
${results
  .map(
    (r) =>
      `  { id: "${r.id}", label: "${r.label}", src: "/logos/${r.id}.webp", width: ${r.width}, height: ${r.height} },`
  )
  .join("\n")}
] as const;
`;

  await writeFile(MANIFEST, ts, "utf8");

  console.log(`\n  ${results.length} logos, ${totalBytes} B total, manifest written to lib/logos.generated.ts\n`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
