/**
 * Builds the video testimonial poster images.
 *
 * WHY POSTERS EXIST AT ALL
 *
 * Because the alternative is three YouTube iframes, and that would undo most of
 * this rebuild. An embedded YouTube player is roughly 700 KB to 1 MB of
 * JavaScript, CSS and images per instance, plus a dozen requests to several
 * third-party origins, plus cookies, and it all runs whether or not anyone ever
 * presses play. Three of them on a page whose entire budget is 274 KB is not a
 * tradeoff, it is a rewrite of the brief.
 *
 * The facade pattern instead: ship a poster image and a play button that look
 * exactly like a player, and load the real thing only when someone asks for it.
 * The page stays at zero third-party requests until a deliberate click.
 *
 * WHERE THE ARTWORK COMES FROM
 *
 * YouTube's own maxresdefault frame for each video, at 1280x720. Propsoch also
 * publishes designed posters at websiteAssets/testimonial/, but those are
 * 565x351, which is both smaller than we need for a 2x render and a 1.61 aspect
 * ratio rather than 16:9. A poster that is not the player's aspect ratio has to
 * be letterboxed or cropped, and either one looks like a mistake. The YouTube
 * frame is true 16:9 and is literally the first frame of what plays, so the
 * poster and the video agree.
 *
 * SIZING
 *
 * 720px wide. The cards render about 373px across at the 1200px layout, so this
 * is a touch under 2x, which is the right place to stop for a photograph: the
 * difference between 1.9x and 2x on a photo is invisible, and the difference in
 * bytes is not. Quality 75 was chosen by encoding the set at 68, 76 and 84 and
 * taking the knee of the curve.
 *
 * Every poster is lazy-loaded and below the fold, so none of this weight is on
 * the critical path, and each is emitted with its exact dimensions into
 * lib/posters.generated.ts so the card can reserve its box and hold CLS at zero.
 *
 *   node scripts/fetch-posters.mjs
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

/**
 * The three testimonial videos.
 *
 * These ids are the same ones in TESTIMONIALS in lib/content.ts, which is where
 * the words live. Keep the two in step: this file owns the pixels, that one
 * owns the copy.
 */
const VIDEOS = [
  { id: "OZMT9fgbH_c", who: "Bharat Singh and Neerja Ahuja" },
  { id: "Nid3XKVEApg", who: "Dr. Ankita Srivastava and Vishal Srivastava" },
  { id: "XrsfHS7tCN0", who: "D.L. Narasimham" },
];

const WIDTH = 720;
const QUALITY = 75;

const OUT_DIR = path.join(process.cwd(), "public", "posters");
const MANIFEST = path.join(process.cwd(), "lib", "posters.generated.ts");

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const results = [];
  let total = 0;

  for (const video of VIDEOS) {
    const url = `https://img.youtube.com/vi/${video.id}/maxresdefault.jpg`;
    const res = await fetch(url, { headers: { "user-agent": "Mozilla/5.0" } });
    if (!res.ok) throw new Error(`${video.id}: HTTP ${res.status} for ${url}`);
    const buf = Buffer.from(await res.arrayBuffer());

    const meta = await sharp(buf).metadata();
    const out = await sharp(buf)
      .resize({ width: WIDTH, kernel: "lanczos3" })
      .webp({ quality: QUALITY, effort: 6 })
      .toBuffer({ resolveWithObject: true });

    await writeFile(path.join(OUT_DIR, `${video.id}.webp`), out.data);
    total += out.data.length;

    results.push({
      id: video.id,
      who: video.who,
      width: out.info.width,
      height: out.info.height,
    });

    console.log(
      `  ${video.id}  ${meta.width}x${meta.height} -> ` +
        `${out.info.width}x${out.info.height}  ${String(out.data.length).padStart(6)}B  ${video.who}`
    );
  }

  const ts = `/**
 * GENERATED by scripts/fetch-posters.mjs. Do not edit by hand.
 *
 * Intrinsic dimensions of the poster WebPs in public/posters. The card renders
 * these as the img width and height so the browser reserves a correctly shaped
 * box before the bytes arrive, which is what holds CLS at zero while three
 * lazy images stream in.
 */

export interface VideoPoster {
  readonly src: string;
  readonly width: number;
  readonly height: number;
}

/** Keyed by YouTube id, the same ids used by TESTIMONIALS in lib/content.ts. */
export const POSTERS: Readonly<Record<string, VideoPoster>> = {
${results
  .map(
    (r) =>
      `  "${r.id}": { src: "/posters/${r.id}.webp", width: ${r.width}, height: ${r.height} },`
  )
  .join("\n")}
};
`;

  await writeFile(MANIFEST, ts, "utf8");
  console.log(
    `\n  ${results.length} posters, ${(total / 1024).toFixed(1)} KB total, manifest written to lib/posters.generated.ts\n`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
