// Downloads YouTube poster frames so no iframe loads before a click.
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const VIDEOS = [
  { id: "OZMT9fgbH_c", who: "Bharat Singh and Neerja Ahuja" },
  { id: "Nid3XKVEApg", who: "Dr. Ankita Srivastava and Vishal Srivastava" },
  { id: "XrsfHS7tCN0", who: "D.L. Narasimham" },
];

const WIDTH = 720;
const QUALITY = 75;

const OUT_DIR = path.join(process.cwd(), "public", "posters");
const MANIFEST = path.join(process.cwd(), "lib", "posters.generated.ts");

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const results = [];
  let total = 0;

  for (const video of VIDEOS) {
    const url = `https://img.youtube.com/vi/${video.id}/maxresdefault.jpg`;
    const res = await fetch(url, { headers: { "user-agent": "Mozilla/5.0" } });
    if (!res.ok) throw new Error(`${video.id}: HTTP ${res.status} for ${url}`);
    const buf = Buffer.from(await res.arrayBuffer());

    const meta = await sharp(buf).metadata();
    const out = await sharp(buf)
      .resize({ width: WIDTH, kernel: "lanczos3" })
      .webp({ quality: QUALITY, effort: 6 })
      .toBuffer({ resolveWithObject: true });

    await writeFile(path.join(OUT_DIR, `${video.id}.webp`), out.data);
    total += out.data.length;

    results.push({
      id: video.id,
      who: video.who,
      width: out.info.width,
      height: out.info.height,
    });

    console.log(
      `  ${video.id}  ${meta.width}x${meta.height} -> ` +
        `${out.info.width}x${out.info.height}  ${String(out.data.length).padStart(6)}B  ${video.who}`
    );
  }

  const ts = `// Generated by scripts/fetch-posters.mjs. Do not edit by hand.

export interface VideoPoster {
  readonly src: string;
  readonly width: number;
  readonly height: number;
}

/** Keyed by YouTube id, the same ids used by TESTIMONIALS in lib/content.ts. */
export const POSTERS: Readonly<Record<string, VideoPoster>> = {
${results
  .map(
    (r) =>
      `  "${r.id}": { src: "/posters/${r.id}.webp", width: ${r.width}, height: ${r.height} },`
  )
  .join("\n")}
};
`;

  await writeFile(MANIFEST, ts, "utf8");
  console.log(
    `\n  ${results.length} posters, ${(total / 1024).toFixed(1)} KB total, manifest written to lib/posters.generated.ts\n`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
